import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1480, height: 940 } })
await p.goto('http://127.0.0.1:4173')
await p.evaluate(() => { const s = window.__kacl.seedState('tabshot'); localStorage.setItem('kacl.doc.v1', JSON.stringify(s)) })
await p.reload({ waitUntil: 'networkidle' })
await p.waitForSelector('text=批次流程看板')
await p.screenshot({ path: '/tmp/shot-board.png', fullPage: true })
await p.click('[data-testid="tab-booking"]')
await p.waitForTimeout(100)
await p.fill('[data-testid="bk-start"]','2099-03-10T09:00'); await p.fill('[data-testid="bk-end"]','2099-03-10T10:00')
await p.click('[data-testid="bk-submit"]'); await p.waitForTimeout(150)
await p.fill('[data-testid="bk-start"]','2099-03-10T09:30'); await p.fill('[data-testid="bk-end"]','2099-03-10T10:30')
await p.waitForTimeout(150)
await p.screenshot({ path: '/tmp/shot-conflict.png', fullPage: true })
await p.click('[data-testid="tab-audit"]'); await p.waitForTimeout(100)
await p.screenshot({ path: '/tmp/shot-audit.png', fullPage: true })
console.log('shots done')
await b.close()
